package ui.main;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.TimeZone;
import javax.swing.Timer;

public class HomeSlide extends javax.swing.JPanel {
 
    public HomeSlide() {
        initComponents();
        updateTimeLabels();
    }
    
    private void updateTimeLabels() {
        Timer timer = new Timer(1000, e -> {
            Calendar calendar = Calendar.getInstance(TimeZone.getDefault());
            SimpleDateFormat hourFormat = new SimpleDateFormat("HH");
            SimpleDateFormat minuteFormat = new SimpleDateFormat("mm");
            SimpleDateFormat secondFormat = new SimpleDateFormat("ss");

            // Cập nhật giờ, phút và giây cho từng JLabel
            lbHour.setText(hourFormat.format(calendar.getTime()));
            lbMinute.setText(minuteFormat.format(calendar.getTime()));
            lbSecond.setText(secondFormat.format(calendar.getTime()));

            // Căn giữa theo chiều ngang và chiều dọc cho JLabel
            lbHour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lbHour.setVerticalAlignment(javax.swing.SwingConstants.CENTER);

            lbMinute.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lbMinute.setVerticalAlignment(javax.swing.SwingConstants.CENTER);

            lbSecond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lbSecond.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        });
        timer.start();  // Bắt đầu đồng hồ chạy mỗi giây
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCenter = new javax.swing.JPanel();
        pHour = new javax.swing.JPanel();
        lbHour = new javax.swing.JLabel();
        pMinute = new javax.swing.JPanel();
        lbMinute = new javax.swing.JLabel();
        pSecond = new javax.swing.JPanel();
        lbSecond = new javax.swing.JLabel();
        slideShow = new ui.menu.SlideShow();

        setPreferredSize(new java.awt.Dimension(1620, 1000));
        setLayout(new java.awt.BorderLayout());

        pCenter.setBackground(new java.awt.Color(255, 255, 255));

        pHour.setBackground(new java.awt.Color(102, 204, 255));

        lbHour.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbHour.setForeground(new java.awt.Color(255, 255, 255));
        lbHour.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout pHourLayout = new javax.swing.GroupLayout(pHour);
        pHour.setLayout(pHourLayout);
        pHourLayout.setHorizontalGroup(
            pHourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pHourLayout.setVerticalGroup(
            pHourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pMinute.setBackground(new java.awt.Color(102, 204, 255));

        lbMinute.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbMinute.setForeground(new java.awt.Color(255, 255, 255));
        lbMinute.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout pMinuteLayout = new javax.swing.GroupLayout(pMinute);
        pMinute.setLayout(pMinuteLayout);
        pMinuteLayout.setHorizontalGroup(
            pMinuteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMinute, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pMinuteLayout.setVerticalGroup(
            pMinuteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMinute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pSecond.setBackground(new java.awt.Color(102, 204, 255));

        lbSecond.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbSecond.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pSecondLayout = new javax.swing.GroupLayout(pSecond);
        pSecond.setLayout(pSecondLayout);
        pSecondLayout.setHorizontalGroup(
            pSecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSecond, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pSecondLayout.setVerticalGroup(
            pSecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSecond, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        slideShow.setText("HỆ THỐNG QUẢN LÝ HIỆU THUỐC TÂY DNGH");
        slideShow.setIconTextGap(30);

        javax.swing.GroupLayout pCenterLayout = new javax.swing.GroupLayout(pCenter);
        pCenter.setLayout(pCenterLayout);
        pCenterLayout.setHorizontalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCenterLayout.createSequentialGroup()
                .addGap(645, 645, 645)
                .addComponent(pHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCenterLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(slideShow, javax.swing.GroupLayout.PREFERRED_SIZE, 1406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        pCenterLayout.setVerticalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCenterLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(slideShow, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        add(pCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbHour;
    private javax.swing.JLabel lbMinute;
    private javax.swing.JLabel lbSecond;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pHour;
    private javax.swing.JPanel pMinute;
    private javax.swing.JPanel pSecond;
    private ui.menu.SlideShow slideShow;
    // End of variables declaration//GEN-END:variables
}
