package ui.main;

import model.*;

import service.OrderDetailService;
import service.OrderService;
import service.ProductService;
import staticProcess.StaticProcess;
import ui.dialog.Confirm;
import ui.dialog.Message;
import ui.dialog.ProductConfirm;
import ui.forms.TempOrderForm;
import ui.table.TableCustom;

import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
@SuppressWarnings("all")

public class ProcessOrder extends JFrame implements ActionListener {

    OrderService orderService = (OrderService) Naming.lookup("rmi://" + StaticProcess.properties.get("ServerName") + ":" + StaticProcess.properties.get("Port") + "/orderService");
    OrderDetailService orderDetailService = (OrderDetailService) Naming.lookup("rmi://" + StaticProcess.properties.get("ServerName") + ":" + StaticProcess.properties.get("Port") + "/orderDetailService");
    ProductService productService = (ProductService) Naming.lookup("rmi://" + StaticProcess.properties.get("ServerName") + ":" + StaticProcess.properties.get("Port") + "/productService");
    private Order orderTemp = new Order();
    private List<OrderDetail> listOrderConfirm = new ArrayList<>();
    private List<OrderDetail>  listOrderDetailConver = new ArrayList<>();
    private List<OrderDetail>  orderDetailsTemp = new ArrayList<>();
    public boolean isUpdating = false;
    NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
    /**
     * Creates new form frmProcessOrder
     */
    public ProcessOrder() throws MalformedURLException, NotBoundException, RemoteException {
        initComponents();
        panelProcess1.pnlHoanTien.setVisible(false);
        panelProcess1.pnlDoiSanPham.setVisible(false);
        JTableHeader header = tblCTHD.getTableHeader();
        header.setBackground(Color.WHITE); 
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                                                       boolean isSelected, boolean hasFocus, int row, int column) {
            Component comp = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            comp.setBackground(Color.WHITE);
            return comp;
        }
        });
        cpCTHD.getViewport().setBackground(Color.WHITE); 
        cpCTHD.setBackground(Color.WHITE);
        tblCTHD.setSelectionBackground(new Color(102, 204, 255));
        tblCTHD.setRowHeight(30);
        TableCustom.apply(cpSanPhamTra, TableCustom.TableType.DEFAULT);
        cpSanPhamTra.getViewport().setBackground(Color.WHITE); 
        cpSanPhamTra.setBackground(Color.WHITE); 
        TableCustom.apply(panelProcess1.cpThemSP, TableCustom.TableType.DEFAULT);
        panelProcess1.cpThemSP.getViewport().setBackground(Color.WHITE); 
        panelProcess1.cpThemSP.setBackground(Color.WHITE); 
        
        cboLoaiXuLy.setBackground(Color.WHITE);

        btnSearch.addActionListener(this);
    }
     public JPanel getPnlProcessPanel(){
         return pnlProcessOrder;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shadowRenderer1 = new ui.swing.shadow.ShadowRenderer();
        lbLogo = new JLabel();
        menu = new ui.menu.Menu();
        pNorth = new JPanel();
        lbHeaderDate = new JLabel();
        btnGuide = new ui.button.Button();
        btnNotification = new ui.button.Button();
        btnAvatar = new ui.button.Button();
        pnlProcessOrder = new ui.panel.PanelRound();
        panelRound4 = new ui.panel.PanelRound();
        jLabel1 = new JLabel();
        panelRound2 = new ui.panel.PanelRound();
        jLabel2 = new JLabel();
        txtSearch = new ui.textfield.TextField_Behind();
        btnSearch = new ui.button.Button();
        panelRound5 = new ui.panel.PanelRound();
        jLabel14 = new JLabel();
        jLabel5 = new JLabel();
        lbltxtMaHoaDon = new JLabel();
        jLabel7 = new JLabel();
        lbltxtKhachHang = new JLabel();
        jLabel8 = new JLabel();
        lbltxtNhanVien = new JLabel();
        jLabel10 = new JLabel();
        lbltxtThoiGianTao = new JLabel();
        jLabel12 = new JLabel();
        lbltxtTongTienTT = new JLabel();
        jLabel3 = new JLabel();
        cpCTHD = new JScrollPane();
        tblCTHD = new JTable();
        panelRound3 = new ui.panel.PanelRound();
        panelRound7 = new ui.panel.PanelRound();
        jLabel16 = new JLabel();
        cboLoaiXuLy = new ui.combo_suggestion.ComboBoxSuggestion<>();
        jLabel15 = new JLabel();
        cpSanPhamTra = new JScrollPane();
        tblSanPhamTra = new JTable();
        jPanel1 = new JPanel();
        panelProcess1 = new ui.custom.PanelProcess();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(242, 249, 242));

        lbLogo.setIcon(new ImageIcon("src/main/java/ui/menu/logoleft.png")); // NOI18N
        lbLogo.setPreferredSize(new Dimension(329, 200));

        pNorth.setBackground(new Color(102, 204, 255));
        pNorth.setPreferredSize(new Dimension(756, 75));

        lbHeaderDate.setFont(new Font("Segoe UI", 1, 20)); // NOI18N
        lbHeaderDate.setForeground(new Color(255, 255, 255));

        btnGuide.setBackground(new Color(102, 204, 255));
        btnGuide.setIcon(new ImageIcon("src/main/java/ui/button/information_32.png")); // NOI18N
        btnGuide.setToolTipText("");
        btnGuide.setRound(50);
        btnGuide.setShadowColor(new Color(102, 204, 255));

        btnNotification.setBackground(new Color(102, 204, 255));
        btnNotification.setIcon(new ImageIcon("src/main/java/ui/button/notification_32.png")); // NOI18N
        btnNotification.setRound(50);
        btnNotification.setShadowColor(new Color(102, 204, 255));

        btnAvatar.setBackground(new Color(102, 204, 255));
        btnAvatar.setIcon(new ImageIcon("src/main/java/ui/button/user_32_white.png")); // NOI18N
        btnAvatar.setRound(50);
        btnAvatar.setShadowColor(new Color(102, 204, 255));

        GroupLayout pNorthLayout = new GroupLayout(pNorth);
        pNorth.setLayout(pNorthLayout);
        pNorthLayout.setHorizontalGroup(
            pNorthLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbHeaderDate, GroupLayout.PREFERRED_SIZE, 512, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvatar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNotification, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuide, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        pNorthLayout.setVerticalGroup(
            pNorthLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pNorthLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(btnNotification, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvatar, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuide, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbHeaderDate, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProcessOrder.setBackground(new Color(242, 249, 255));
        pnlProcessOrder.setForeground(new Color(242, 249, 255));
        pnlProcessOrder.setShadowColor(new Color(242, 249, 255));

        panelRound4.setBackground(new Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(10);
        panelRound4.setRoundBottomRight(10);
        panelRound4.setRoundTopLeft(10);
        panelRound4.setRoundTopRight(10);

        jLabel1.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Xử lý hóa đơn:");

        panelRound2.setBackground(new Color(255, 255, 255));
        panelRound2.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        panelRound2.setRoundBottomLeft(10);
        panelRound2.setRoundBottomRight(10);
        panelRound2.setRoundTopLeft(10);
        panelRound2.setRoundTopRight(10);

        jLabel2.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nhập mã hóa đơn xử lý:");

        txtSearch.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        txtSearch.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new ImageIcon("src/main/java/ui/button/magnifying-glass_32.png")); // NOI18N
        btnSearch.setMargin(new Insets(2, 10, 3, 10));
        btnSearch.setRound(40);
        btnSearch.setBackground(new Color(102, 204, 255));
        btnSearch.setShadowColor(new Color(102, 204, 255));
        GroupLayout panelRound2Layout = new GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, GroupLayout.PREFERRED_SIZE, 282, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelRound2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound5.setBackground(new Color(255, 255, 255));
        panelRound5.setRoundBottomLeft(10);
        panelRound5.setRoundBottomRight(10);
        panelRound5.setRoundTopLeft(10);
        panelRound5.setRoundTopRight(10);

        jLabel14.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Thông tin hóa đơn đã tạo:");

        jLabel5.setFont(new Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setText("Mã hóa đơn:");

        lbltxtMaHoaDon.setFont(new Font("Segoe UI", 0, 20)); // NOI18N
        lbltxtMaHoaDon.setText("---");

        jLabel7.setFont(new Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("Khách hàng:");

        lbltxtKhachHang.setFont(new Font("Segoe UI", 0, 20)); // NOI18N
        lbltxtKhachHang.setText("--- / -----------");

        jLabel8.setFont(new Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setText("Nhân viên tạo:");

        lbltxtNhanVien.setFont(new Font("Segoe UI", 0, 20)); // NOI18N
        lbltxtNhanVien.setText("-- / ------------");

        jLabel10.setFont(new Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Thời gian tạo:");

        lbltxtThoiGianTao.setFont(new Font("Segoe UI", 0, 20)); // NOI18N
        lbltxtThoiGianTao.setText("--/--/----  --:--");

        jLabel12.setFont(new Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setText("Tổng tiền đã thanh toán:");

        lbltxtTongTienTT.setFont(new Font("Segoe UI", 2, 30)); // NOI18N
        lbltxtTongTienTT.setForeground(new Color(255, 0, 0));
        lbltxtTongTienTT.setText("----");

        jLabel3.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Chi tiết hóa đơn:");

        tblCTHD.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        tblCTHD.setModel(new DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Đơn vị", "SL", "Giá bán", "Thành tiền", "Đủ điều kiện", "Xác nhận"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, String.class, String.class, String.class, Integer.class, Double.class, Double.class, Boolean.class, Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cpCTHD.setViewportView(tblCTHD);
        TableColumnModel columnModel = tblCTHD.getColumnModel();
        columnModel.setColumnSelectionAllowed(false); // Ngăn chọn cột
//        columnModel.setReorderingAllowed(false);

        if (tblCTHD.getColumnModel().getColumnCount() > 0) {
            tblCTHD.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblCTHD.getColumnModel().getColumn(4).setPreferredWidth(30);
            tblCTHD.getColumnModel().getColumn(8).setPreferredWidth(80);
        }

        GroupLayout panelRound5Layout = new GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(cpCTHD)
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addGroup(panelRound5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound5Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(panelRound5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 235, GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87)
                                .addGroup(panelRound5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltxtThoiGianTao, GroupLayout.PREFERRED_SIZE, 352, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltxtKhachHang, GroupLayout.PREFERRED_SIZE, 396, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltxtMaHoaDon, GroupLayout.PREFERRED_SIZE, 396, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltxtNhanVien, GroupLayout.PREFERRED_SIZE, 352, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltxtTongTienTT, GroupLayout.PREFERRED_SIZE, 352, GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 310, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 310, GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(12, 12, 12)
                .addGroup(panelRound5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbltxtMaHoaDon))
                .addGap(28, 28, 28)
                .addGroup(panelRound5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbltxtKhachHang))
                .addGap(28, 28, 28)
                .addGroup(panelRound5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbltxtNhanVien)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(panelRound5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtThoiGianTao)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addGroup(panelRound5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtTongTienTT)
                    .addComponent(jLabel12))
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpCTHD, GroupLayout.PREFERRED_SIZE, 417, GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        GroupLayout panelRound4Layout = new GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelRound5, GroupLayout.PREFERRED_SIZE, 795, GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );

        panelRound3.setBackground(new Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(10);
        panelRound3.setRoundBottomRight(10);
        panelRound3.setRoundTopLeft(10);
        panelRound3.setRoundTopRight(10);

        panelRound7.setBackground(new Color(255, 255, 255));
        panelRound7.setRoundBottomLeft(10);
        panelRound7.setRoundBottomRight(10);
        panelRound7.setRoundTopLeft(10);
        panelRound7.setRoundTopRight(10);

        jLabel16.setFont(new Font("Segoe UI", 0, 20)); // NOI18N
        jLabel16.setText("Chọn loại xử lý:");

        cboLoaiXuLy.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        cboLoaiXuLy.setModel(new DefaultComboBoxModel<>(new String[] {"Xử lý hoàn tiền", "Xử lý đổi sản phẩm khác" }));
        cboLoaiXuLy.setSelectedIndex(-1);
        cboLoaiXuLy.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cboLoaiXuLyActionPerformed(evt);
            }
        });

        GroupLayout panelRound7Layout = new GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboLoaiXuLy, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRound7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cboLoaiXuLy, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)))
        );

        jLabel15.setFont(new Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setText("Sản phẩm đã xác nhận đổi trả:");

        cpSanPhamTra.setBackground(new Color(255, 255, 255));

        tblSanPhamTra.setModel(new DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá bán"
            }
        ));
        cpSanPhamTra.setViewportView(tblSanPhamTra);

        jPanel1.setBackground(new Color(255, 255, 255));

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelProcess1, GroupLayout.PREFERRED_SIZE, 736, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(panelProcess1, GroupLayout.PREFERRED_SIZE, 598, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        GroupLayout panelRound3Layout = new GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelRound7, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, GroupLayout.Alignment.LEADING)
                        .addComponent(cpSanPhamTra, GroupLayout.Alignment.LEADING))))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpSanPhamTra, GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        GroupLayout pnlProcessOrderLayout = new GroupLayout(pnlProcessOrder);
        pnlProcessOrder.setLayout(pnlProcessOrderLayout);
        pnlProcessOrderLayout.setHorizontalGroup(
            pnlProcessOrderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcessOrderLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlProcessOrderLayout.setVerticalGroup(
            pnlProcessOrderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcessOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProcessOrderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProcessOrderLayout.createSequentialGroup()
                        .addComponent(panelRound3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(panelRound4, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 973, Short.MAX_VALUE))
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogo, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(pNorth, GroupLayout.DEFAULT_SIZE, 1614, Short.MAX_VALUE)
                    .addComponent(pnlProcessOrder, GroupLayout.PREFERRED_SIZE, 1614, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pNorth, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlProcessOrder, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbLogo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(menu, GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelProcess1.btnT.addActionListener(this);
        panelProcess1.btnDThem.addActionListener(this);
        panelProcess1.btnD.addActionListener(this);
        pack();

        //Xử lý sự kiện trên bảng chi tiết hóa đơn
        tblCTHD.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (isUpdating) {
                    return;
                }
                listOrderConfirm = new ArrayList<>();
                for (int i = 0; i < tblCTHD.getModel().getRowCount(); i++) {

                    Boolean checked = (Boolean) tblCTHD.getModel().getValueAt(i, 8);
                    if (checked != null && checked) {
                        OrderDetail odt = searchOrderDetail((String) tblCTHD.getModel().getValueAt(i, 1));
                        listOrderConfirm.add(odt);
                        continue;
                    }
                    if (checked != null && checked) {
                        if (!((Boolean) tblCTHD.getModel().getValueAt(i, 7))) {
                            Confirm dialog = new Confirm(StaticProcess.homePage, true, "Chú ý", "Lưu ý đây là những sản phẩm không cho đổi trả trừ trường hợp giao nhầm. Bạn vẫn muốn tiếp tục?", "src/main/java/ui/dialog/warning.png", "Tiếp tục", "Hủy bỏ");
                            dialog.showAlert();
                            int response = dialog.getResponse();
                            if (response == 1) {
                                OrderDetail odt = searchOrderDetail((String) tblCTHD.getModel().getValueAt(i, 1));
                                if (odt != null) {
                                    listOrderConfirm.add(odt);
                                }
                            } else {
                                tblCTHD.getModel().setValueAt(false, i, 8);
                            }
                        } else{
                            OrderDetail odt = searchOrderDetail((String) tblCTHD.getModel().getValueAt(i, 1));
                            if (odt != null) {
                                listOrderConfirm.add(odt);
                            }
                        }
                    }
                }
                infoRefund();
                loadTableSPTra(tblSanPhamTra, listOrderConfirm);
            }
        });


        txtSearch.addActionListener(e -> {
            btnSearch.doClick();
        });
        panelProcess1.txtDThem.addActionListener(e -> {
            panelProcess1.btnDThem.doClick();
        });
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void cboLoaiXuLyActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cboLoaiXuLyActionPerformed
        // TODO add your handling code here:
        if(((String)cboLoaiXuLy.getSelectedItem()).equals("Xử lý hoàn tiền")){
            panelProcess1.pnlHoanTien.setVisible(true);
            panelProcess1.pnlDoiSanPham.setVisible(false);
        } else if (((String)cboLoaiXuLy.getSelectedItem()).equals("Xử lý đổi sản phẩm khác")){
            panelProcess1.pnlHoanTien.setVisible(false);
            panelProcess1.pnlDoiSanPham.setVisible(true);
        } else {
            panelProcess1.pnlHoanTien.setVisible(false);
            panelProcess1.pnlDoiSanPham.setVisible(false);
        }
    }//GEN-LAST:event_cboLoaiXuLyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcessOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProcessOrder().setVisible(true);
                } catch (MalformedURLException e) {
                    throw new RuntimeException(e);
                } catch (NotBoundException e) {
                    throw new RuntimeException(e);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.button.Button btnAvatar;
    private ui.button.Button btnGuide;
    private ui.button.Button btnNotification;
    private ui.button.Button btnSearch;
    private ui.combo_suggestion.ComboBoxSuggestion<String> cboLoaiXuLy;
    private JScrollPane cpCTHD;
    private JScrollPane cpSanPhamTra;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel12;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel5;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JPanel jPanel1;
    private JLabel lbHeaderDate;
    private JLabel lbLogo;
    private JLabel lbltxtKhachHang;
    private JLabel lbltxtMaHoaDon;
    private JLabel lbltxtNhanVien;
    private JLabel lbltxtThoiGianTao;
    private JLabel lbltxtTongTienTT;
    private ui.menu.Menu menu;
    private JPanel pNorth;
    private ui.custom.PanelProcess panelProcess1;
    private ui.panel.PanelRound panelRound2;
    private ui.panel.PanelRound panelRound3;
    private ui.panel.PanelRound panelRound4;
    private ui.panel.PanelRound panelRound5;
    private ui.panel.PanelRound panelRound7;
    private ui.panel.PanelRound pnlProcessOrder;
    private ui.swing.shadow.ShadowRenderer shadowRenderer1;
    private JTable tblCTHD;
    private JTable tblSanPhamTra;
    private ui.textfield.TextField_Behind txtSearch;

    @Override
    public void actionPerformed(ActionEvent e) {
        Object o = e.getSource();
        if(o.equals(btnSearch)){
            if(txtSearch.getText().trim().equals("")){
                new Message(StaticProcess.homePage, true, "Thông báo", "Vui lòng nhập mã hóa đơn đổi trả", "src/main/java/ui/dialog/warning.png").showAlert();
            }else{
                try {
                    orderTemp = orderService.findById(txtSearch.getText());
                } catch (RemoteException ex) {
                    throw new RuntimeException(ex);
                }
                if(orderTemp.getCustomer() == null){
                    new Message(StaticProcess.homePage, true, "Thông báo", "Hóa đơn khách vãng lai, không được đổi trả theo quy định!", "src/main/java/ui/dialog/warning.png").showAlert();
                }
                if(orderTemp == null){
                    new Message(StaticProcess.homePage, true, "Thông báo", "Hóa đơn không tồn tại, vui lòng kiểm tra lại", "src/main/java/ui/dialog/warning.png").showAlert();
                }else{
                    try {
                        BarcodeGenerator.generateBarcode(txtSearch.getText().trim());
                    } catch (com.itextpdf.barcodes.qrcode.WriterException | IOException ex) {
                        throw new RuntimeException(ex);
                    }

                    try {
                        if(orderService.orderIsExists(convertOrderID(orderTemp.getOrderID()))){
                            new Message(StaticProcess.homePage, true, "Thông báo", "Hóa đơn này đã được đổi trả, vui lòng kiểm tra lại", "src/main/java/ui/dialog/warning.png").showAlert();
                        }else{
                            orderDetailsTemp = orderTemp.getListOrderDetail();
                            fillInfo(orderTemp);
                            loadTableCTHD(tblCTHD, orderDetailsTemp);
                        }
                    } catch (RemoteException ex) {
                        throw new RuntimeException(ex);
                    }
                }
            }
        }
        //Xử lý xác nhận hoàn tiền
        if(o.equals(panelProcess1.btnT) && checkOrder()){
            if(listOrderConfirm.size() != 0){
                if(panelProcess1.chkTXacNhan.isSelected()){
                    Order orderN = new Order(convertOrderID(orderTemp.getOrderID()), LocalDateTime.now(), orderTemp.getShipToAddress(), orderTemp.getPaymentMethod(), orderTemp.getDiscount(), StaticProcess.empLogin, orderTemp.getCustomer(), orderTemp.getPrescription());
                    List<OrderDetail> listOrderDetail = new ArrayList<>();
                    for (OrderDetail ord: listOrderConfirm){
                            listOrderDetail.add(new OrderDetail(orderN, ord.getProduct(), ord.getUnit(), -ord.getOrderQuantity()));
                        try {
                            productService.update(productService.getProductAfterUpdateUnits(ord.getProduct(), ord.getUnit(), true, ord.getOrderQuantity()));
                        } catch (RemoteException ex) {
                            throw new RuntimeException(ex);
                        }
                    }
                    orderN.setListOrderDetail(listOrderDetail);
                    orderN.setDiscount(orderTemp.getDiscount() - orderN.getTotalDue() * 0.01);
                    try {
                        orderService.create(orderN);
                    } catch (RemoteException ex) {
                        throw new RuntimeException(ex);
                    }
                    new Message(StaticProcess.homePage, true, "Thông báo", "Hóa đơn đã được xử lý thành công!", "src/main/java/ui/dialog/done.png").showAlert();
                    reset();
                    try {
                        TempOrderForm.invoiceOrder(orderN);
                    } catch (IOException | NotBoundException ex) {
                        throw new RuntimeException(ex);
                    }
                }else {
                    new Message(StaticProcess.homePage, true, "Chú ý", "Trường hợp hoàn tiền, vui lòng xác nhận đây là hóa đơn với lý do giao nhầm sản phẩm", "src/main/java/ui/dialog/warning.png").showAlert();
                }
            }else {
                new Message(StaticProcess.homePage, true, "Chú ý", "Vui lòng thêm sản phẩm đổi trả", "src/main/java/ui/dialog/warning.png").showAlert();
            }
        }
        //XỬ lý đổi trả sản phẩm
        if(o.equals(panelProcess1.btnDThem)){
            if(checkData()){
                Product prod = null;
                try {
                    prod = productService.findById(convertBarcodeToProductID(panelProcess1.txtDThem.getText()));
                } catch (RemoteException ex) {
                    throw new RuntimeException(ex);
                }
                if(prod != null){
                    ProductConfirm pCf = null;
                    try {
                        pCf = new ProductConfirm(StaticProcess.homePage, prod, true);
                    } catch (MalformedURLException ex) {
                        throw new RuntimeException(ex);
                    } catch (NotBoundException ex) {
                        throw new RuntimeException(ex);
                    } catch (RemoteException ex) {
                        throw new RuntimeException(ex);
                    }
                    pCf.showAlert();
                    OrderDetail pSelect = null;
                    try {
                        pSelect = pCf.getOrderDetails(orderTemp, convertOrderID(orderTemp.getOrderID()));
                    } catch (RemoteException ex) {
                        throw new RuntimeException(ex);
                    }
                    if(checkProductLíst(prod.getProductID(), listOrderDetailConver)){
                        listOrderDetailConver.add(pSelect);
                    }else{
                        for(OrderDetail ot: listOrderDetailConver){
                            if(ot.getProduct().getProductID().equals(prod.getProductID())){
                                ot.setOrderQuantity((ot.getOrderQuantity() + 1));
                            }
                        }
                    }
                    panelProcess1.txtDThem.setText("");
                    fillInfoPC();
                }else{
                    new Message(StaticProcess.homePage, true, "Chú ý", "Sản phẩm không tồn tại!", "src/main/java/ui/dialog/warning.png").showAlert();
                }
                loadTableCTHD(panelProcess1.tblThemSP, listOrderDetailConver);
            }
        }
        //Xác nhận đổi trả sản phẩm
        if(o.equals(panelProcess1.btnD) && checkOrder()){
            if(listOrderConfirm.size() != 0){
                if(listOrderDetailConver.size() == 0){
                    new Message(StaticProcess.homePage, true, "Chú ý", "Vui lòng thêm sản phẩm muốn quy đổi", "src/main/java/ui/dialog/warning.png").showAlert();
                    panelProcess1.txtDThem.requestFocus();
                }else{
                    Order orderD = new Order(convertOrderID(orderTemp.getOrderID()), LocalDateTime.now(), orderTemp.getShipToAddress(), orderTemp.getPaymentMethod(), orderTemp.getDiscount(), StaticProcess.empLogin, orderTemp.getCustomer(), orderTemp.getPrescription());
                    //Thêm chi tiết hóa đơn
                    double tienBanDau = getProductListPrice(listOrderConfirm);
                    double tongDoi = getProductListPrice(listOrderDetailConver);
                    double tienThuThem =  tienBanDau - (tienBanDau * 0.01) - tongDoi;
                    List<OrderDetail> listOrderDetails = new ArrayList<>();
                    double additionalAmount = 0;
                    double addBefore = 0;
                    //Đã xác nhận đổi trả
                    for (int i = 0; i < listOrderConfirm.size(); i++){
                        OrderDetail ord = listOrderConfirm.get(i);
                        addBefore += ord.getLineTotal();
                        //Sản phẩm trả tăng số lượng tồn kho
                        try {
                            productService.update(productService.getProductAfterUpdateUnits(ord.getProduct(), ord.getUnit(), true, ord.getOrderQuantity()));
                        } catch (RemoteException ex) {
                            throw new RuntimeException(ex);
                        }
                    }
                    //Cập nhật tình trạng tồn kho
                    //Sản phẩm muốn đổi
                    for(OrderDetail ot: listOrderDetailConver){
                        try {
                            additionalAmount += ot.getLineTotal();
                            listOrderDetails.add(new OrderDetail(orderD, ot.getProduct(), ot.getUnit(), ot.getOrderQuantity()));
                            productService.update(productService.getProductAfterUpdateUnits(ot.getProduct(), ot.getUnit(), false, ot.getOrderQuantity()));
                        } catch (RemoteException ex) {
                            throw new RuntimeException(ex);
                        }
                    }
                    orderD.setListOrderDetail(listOrderDetailConver);
                    orderD.setDiscount(addBefore - (addBefore * 0.01));
                    //Thêm hóa đơn
                    try {
                        orderService.create(orderD);
                    } catch (RemoteException ex) {
                        throw new RuntimeException(ex);
                    }
                    reset();
                    new Message(StaticProcess.homePage, true, "Thông báo", "Hóa đơn đã được xử lý thành công!", "src/main/java/ui/dialog/done.png").showAlert();
                    try {
                        TempOrderForm.invoiceOrder(orderD);
                    } catch (IOException | NotBoundException ex) {
                        throw new RuntimeException(ex);
                    }
                }
            }else {
                new Message(StaticProcess.homePage, true, "Chú ý", "Vui lòng thêm sản phẩm đổi trả", "src/main/java/ui/dialog/warning.png").showAlert();
            }
        }
    }
    // End of variables declaration//GEN-END:variables

//Kiểm tra điều kiện thêm sản phẩm
    public boolean checkData(){
        if(orderDetailsTemp.isEmpty()){
            new Message(StaticProcess.homePage, true, "Chú ý", "Vui lòng tìm hóa đơn đổi trả", "src/main/java/ui/dialog/warning.png").showAlert();
            panelProcess1.txtDThem.setText("");
            txtSearch.requestFocus();
            return false;
        }
        if(panelProcess1.txtDThem.getText().trim().equals("")){
            new Message(StaticProcess.homePage, true, "Chú ý", "Vui lòng nhập mã sản phẩm quy đổi", "src/main/java/ui/dialog/warning.png").showAlert();
            panelProcess1.txtDThem.requestFocus();
            return false;
        }
        return true;
    }

    //Hóa đơn tạm đã tồn tại chưa
    public boolean checkOrder(){
        if(txtSearch.getText().trim().equals("")){
            new Message(StaticProcess.homePage, true, "Thông báo", "Vui lòng nhập mã hóa đơn đổi trả", "src/main/java/ui/dialog/warning.png").showAlert();
            txtSearch.requestFocus();
            return false;
        }
        return true;
    }

    public void fillInfo(Order o){
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
           lbltxtMaHoaDon.setText(o.getOrderID());
           lbltxtKhachHang.setText(o.getCustomer().getCustomerID() + " / " + o.getCustomer().getCustomerName());
           lbltxtNhanVien.setText(o.getEmployee().getEmployeeID() + " / " + o.getEmployee().getEmployeeName());
           lbltxtThoiGianTao.setText(o.getOrderDate().format(formatter));
           lbltxtTongTienTT.setText(currencyFormatter.format(o.getTotalDue()));
    }

    public void loadTableCTHD(JTable table, List<OrderDetail> listCTHD){
        isUpdating = true;
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        int count = 1;
        for (OrderDetail o : listCTHD){
            model.addRow(new Object[] {count, o.getProduct().getProductID(), o.getProduct().getProductName(), o.getUnit().name(), o.getOrderQuantity(), o.getLineTotal()/o.getOrderQuantity(), o.getLineTotal(), checkCondition(o), false});
            count++;
        }
        isUpdating = false;
    }

    public void loadTableSPTra(JTable table, List<OrderDetail> listCTHD){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        int count = 1; //"STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá bán", "Thành tiền"
        for (OrderDetail o : listCTHD){
            model.addRow(new Object[] {count, o.getProduct().getProductID(), o.getProduct().getProductName(), o.getOrderQuantity(), o.getLineTotal()});
            count++;
        }
    }

    public boolean checkCondition(OrderDetail odt){
            LocalDateTime currentDateTime = LocalDateTime.now();
            LocalDateTime thirtyDaysAgo = currentDateTime.minus(30, ChronoUnit.DAYS);
            if (odt.getProduct().isFunctionalFood() && (!orderTemp.getCustomer().getPhoneNumber().equals("")) && orderTemp.getOrderDate().isAfter(thirtyDaysAgo)){
                return true;
            }
            return false;
    }

    public OrderDetail searchOrderDetail(String productID){
            for(OrderDetail odt : orderDetailsTemp){
                if(odt.getProduct().getProductID().equals(productID)){
                    return odt;
                }
            }
            return null;
    }

    //Xử lý thông tin hoàn tiền
        public void infoRefund(){
            panelProcess1.lbltxtTS_SPC.setText(listOrderConfirm.size() + "");
            double tienHoan = 0.0;
            for(OrderDetail odt : listOrderConfirm){
                tienHoan += odt.getLineTotal();
            }
            panelProcess1.lbltxtTTongTien.setText(currencyFormatter.format(tienHoan));
            panelProcess1.lbltxtTPhiHoanTien.setText(currencyFormatter.format(tienHoan * 0.01));
            panelProcess1.lbltxtTTongHoanTien.setText(currencyFormatter.format(tienHoan - (tienHoan * 0.01)));
        }
    //=========================================================================================
    //Đối với hoàn tiền nó sẽ tạo ra hóa đơn mới với tổng tiền là số âm, vd mã hóa đơn đổi trả OR101124000001 thì tạo hóa đơn mới với mã là OC101124000001

    //Hàm chuyển đổi mã háo đơn
    public String convertOrderID(String orderID) {
        if (orderID.length() >= 3) {
            StringBuilder modifiedCode = new StringBuilder(orderID);
            modifiedCode.setCharAt(1, 'C');
            return modifiedCode.toString();
        }
        return orderID;
    }

    //Hàm đặt lại khi hóa đơn xử lý thành công
    public void reset(){
        txtSearch.setText("");
        lbltxtMaHoaDon.setText("---");
        lbltxtKhachHang.setText("--- / ---" );
        lbltxtNhanVien.setText("--- / ---");
        lbltxtThoiGianTao.setText("---");
        lbltxtTongTienTT.setText("---");

        orderTemp = new Order();
        orderDetailsTemp = new ArrayList<>();
        listOrderConfirm = new ArrayList<>();
        listOrderDetailConver = new ArrayList<>();
        loadTableCTHD(tblCTHD, orderDetailsTemp);
        loadTableSPTra(tblSanPhamTra, listOrderConfirm);
        loadTableCTHD(panelProcess1.tblThemSP, listOrderDetailConver);

        //Thêm tin bên đổi sản phẩm
        panelProcess1.lblDTienBD.setText("---");
        panelProcess1.lblDTienQuyDoi.setText("---");
        panelProcess1.lbltxtChiPhiThem.setText("---");
        panelProcess1.lbltxtTienHoanThem.setText("---");
        //Thông tin bên hoàn tiền
        panelProcess1.lbltxtTS_SPC.setText("");
        panelProcess1.lbltxtTTongTien.setText("---");
        panelProcess1.lbltxtTPhiHoanTien.setText("---");
        panelProcess1.lbltxtTTongHoanTien.setText("---");

        cboLoaiXuLy.setSelectedIndex(0);
    }

    //Hàm chuyển đổi về barcode
    private String convertProductIDToBarcode(String productID) {
        if (productID == null || productID.length() < 2) {
            return null;
        }
        String prefix = productID.substring(0, 2);
        String numericPart = productID.substring(2);
        switch (prefix) {
            case "PF":
                return "7" + numericPart;
            case "PM":
                return "8" + numericPart;
            case "PS":
                return "9" + numericPart;
            default:
                return null;
        }
    }

    //Hàm chuyển đổi ngược lại
    private String convertBarcodeToProductID(String barcode) {
        if (barcode == null || barcode.length() < 2) {
            return null;
        }
        char prefix = barcode.charAt(0);
        String numericPart = barcode.substring(1);
        switch (prefix) {
            case '7':
                return "PF" + numericPart;
            case '8':
                return "PM" + numericPart;
            case '9':
                return "PS" + numericPart;
            default:
                return null;
        }
    }

    //Hàm addRow
    private void addRow(JTable table, ArrayList<Product> listProduct, int quantity){
        DecimalFormat df = new DecimalFormat("#,##0.00 VND");
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        int count = 1;
        for (Product o : listProduct){
            model.addRow(new Object[] {count, o.getProductID(), o.getProductName(), });
    //        Object[] rowData = {product.getProductID(), product.getProductName(), "Đơn vị", quantity, df.format(product.getSellPrice()), df.format(quantity * product.getSellPrice())};
            count++;
        }
    }
    /**
     * Kiểm tra mã sản phẩm có tồn tại trong cột 2 của bảng hay không.
     *
     * @param table      Đối tượng JTable
     * @param productID  Mã sản phẩm cần kiểm tra
     * @return true nếu mã sản phẩm tồn tại, false nếu không
     */
    private boolean isProductExists(JTable table, String productID) {
        int rowCount = table.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            Object value = table.getValueAt(i, 1);
            if (value != null && value.toString().equals(productID)) {
                return true;
            }
        }
        return false;
    }
    public boolean checkProductLíst(String productID, List<OrderDetail> listOdt){
        for(OrderDetail odt : listOdt){
            if(odt.getProduct().getProductID().equals(productID))
                return false;
        }
        return true;
    }

    //Get tổng tiền đổi trả sản phẩm
    public double getProductListPrice(List<OrderDetail> list){
        double t = 0;
        for(OrderDetail o : list){
            t += o.getLineTotal();
        }
        return t;
    }

    //Load thông tin tổng quan đổi trả hàng
    public void fillInfoPC(){
        double tienBanDau = getProductListPrice(listOrderConfirm);
        double tienSanPhamDoi = getProductListPrice(listOrderDetailConver);
        panelProcess1.lblDTienBD.setText(currencyFormatter.format(tienBanDau));
        panelProcess1.lblDTienQuyDoi.setText(currencyFormatter.format(tienSanPhamDoi));
        //tiền ban đầu - thuế - tiền sản phẩm quy đổi = số tiền của khách hàng
        double tienThuThem =  tienBanDau - (tienBanDau * 0.01) - tienSanPhamDoi;
        panelProcess1.lbltxtChiPhiThem.setText(tienThuThem>0?currencyFormatter.format(0.0):currencyFormatter.format(tienThuThem * (-1)));
        panelProcess1.lbltxtTienHoanThem.setText(tienThuThem>0?currencyFormatter.format(tienThuThem):currencyFormatter.format(0.0));
    }

}

